export const users = [
  {
    id: "01",
    name: "Robert Fox",
    email: "fox@email",
    status: "Paid",
    date: "02-24-2024",
    avatar: "https://i.pravatar.cc/40?img=1",
    plan: "Monthly",
  },
  {
    id: "02",
    name: "Mark Henry",
    email: "markhenry@email",
    status: "Paid",
    date: "02-24-2024",
    avatar: "https://i.pravatar.cc/40?img=2",
    plan: "Monthly",
  },
  {
    id: "03",
    name: "Shifat",
    email: "shifat@email",
    status: "Paid",
    date: "02-24-2024",
    avatar: "https://i.pravatar.cc/40?img=3",
    plan: "6 Months",
  },
  {
    id: "04",
    name: "John Doe",
    email: "johndoe@email",
    status: "Paid",
    date: "02-24-2024",
    avatar: "https://i.pravatar.cc/40?img=4",
    plan: "6 Months",
  },
  {
    id: "05",
    name: "Robert Fox",
    email: "fox2@email",
    status: "Expired",
    date: "02-24-2024",
    avatar: "https://i.pravatar.cc/40?img=5",
    plan: "Yearly",
  },
  {
    id: "06",
    name: "Mark Henry",
    email: "markhenry2@email",
    status: "Expired",
    date: "02-24-2024",
    avatar: "https://i.pravatar.cc/40?img=6",
    plan: "Yearly",
  },
  {
    id: "07",
    name: "Alice Johnson",
    email: "alice@email",
    status: "Paid",
    date: "02-25-2024",
    avatar: "https://i.pravatar.cc/40?img=7",
    plan: "Monthly",
  },
  {
    id: "08",
    name: "Michael Smith",
    email: "michael@email",
    status: "Expired",
    date: "02-25-2024",
    avatar: "https://i.pravatar.cc/40?img=8",
    plan: "Yearly",
  },
  {
    id: "09",
    name: "Sophia Lee",
    email: "sophia@email",
    status: "Paid",
    date: "02-25-2024",
    avatar: "https://i.pravatar.cc/40?img=9",
    plan: "6 Months",
  },
  {
    id: "10",
    name: "David Miller",
    email: "david@email",
    status: "Expired",
    date: "02-25-2024",
    avatar: "https://i.pravatar.cc/40?img=10",
    plan: "Monthly",
  },
  {
    id: "11",
    name: "Emma Wilson",
    email: "emma@email",
    status: "Paid",
    date: "02-26-2024",
    avatar: "https://i.pravatar.cc/40?img=11",
    plan: "Yearly",
  },
  {
    id: "12",
    name: "Liam Brown",
    email: "liam@email",
    status: "Expired",
    date: "02-26-2024",
    avatar: "https://i.pravatar.cc/40?img=12",
    plan: "6 Months",
  },
  {
    id: "13",
    name: "Olivia Taylor",
    email: "olivia@email",
    status: "Paid",
    date: "02-26-2024",
    avatar: "https://i.pravatar.cc/40?img=13",
    plan: "Monthly",
  },
  {
    id: "14",
    name: "James Anderson",
    email: "james@email",
    status: "Expired",
    date: "02-26-2024",
    avatar: "https://i.pravatar.cc/40?img=14",
    plan: "Yearly",
  },
  {
    id: "15",
    name: "Ava Martinez",
    email: "ava@email",
    status: "Paid",
    date: "02-27-2024",
    avatar: "https://i.pravatar.cc/40?img=15",
    plan: "6 Months",
  },
  {
    id: "16",
    name: "Noah White",
    email: "noah@email",
    status: "Expired",
    date: "02-27-2024",
    avatar: "https://i.pravatar.cc/40?img=16",
    plan: "Monthly",
  },
  {
    id: "17",
    name: "Mia Harris",
    email: "mia@email",
    status: "Paid",
    date: "02-27-2024",
    avatar: "https://i.pravatar.cc/40?img=17",
    plan: "Yearly",
  },
  {
    id: "18",
    name: "Ethan Clark",
    email: "ethan@email",
    status: "Expired",
    date: "02-27-2024",
    avatar: "https://i.pravatar.cc/40?img=18",
    plan: "6 Months",
  },
  {
    id: "19",
    name: "Isabella Lewis",
    email: "isabella@email",
    status: "Paid",
    date: "02-28-2024",
    avatar: "https://i.pravatar.cc/40?img=19",
    plan: "Monthly",
  },
  {
    id: "20",
    name: "William Walker",
    email: "william@email",
    status: "Expired",
    date: "02-28-2024",
    avatar: "https://i.pravatar.cc/40?img=20",
    plan: "Yearly",
  },
  {
    id: "21",
    name: "Charlotte Hall",
    email: "charlotte@email",
    status: "Paid",
    date: "02-28-2024",
    avatar: "https://i.pravatar.cc/40?img=21",
    plan: "Monthly",
  },
  {
    id: "22",
    name: "Benjamin Young",
    email: "benjamin@email",
    status: "Expired",
    date: "02-28-2024",
    avatar: "https://i.pravatar.cc/40?img=22",
    plan: "6 Months",
  },
  {
    id: "23",
    name: "Amelia King",
    email: "amelia@email",
    status: "Paid",
    date: "03-01-2024",
    avatar: "https://i.pravatar.cc/40?img=23",
    plan: "Yearly",
  },
  {
    id: "24",
    name: "Lucas Scott",
    email: "lucas@email",
    status: "Expired",
    date: "03-01-2024",
    avatar: "https://i.pravatar.cc/40?img=24",
    plan: "Monthly",
  },
  {
    id: "25",
    name: "Harper Green",
    email: "harper@email",
    status: "Paid",
    date: "03-01-2024",
    avatar: "https://i.pravatar.cc/40?img=25",
    plan: "6 Months",
  },
  {
    id: "26",
    name: "Daniel Adams",
    email: "daniel@email",
    status: "Expired",
    date: "03-01-2024",
    avatar: "https://i.pravatar.cc/40?img=26",
    plan: "Yearly",
  },
  {
    id: "27",
    name: "Evelyn Baker",
    email: "evelyn@email",
    status: "Paid",
    date: "03-02-2024",
    avatar: "https://i.pravatar.cc/40?img=27",
    plan: "Monthly",
  },
  {
    id: "28",
    name: "Henry Nelson",
    email: "henry@email",
    status: "Expired",
    date: "03-02-2024",
    avatar: "https://i.pravatar.cc/40?img=28",
    plan: "6 Months",
  },
  {
    id: "29",
    name: "Abigail Carter",
    email: "abigail@email",
    status: "Paid",
    date: "03-02-2024",
    avatar: "https://i.pravatar.cc/40?img=29",
    plan: "Yearly",
  },
  {
    id: "30",
    name: "Jack Mitchell",
    email: "jack@email",
    status: "Expired",
    date: "03-02-2024",
    avatar: "https://i.pravatar.cc/40?img=30",
    plan: "Monthly",
  },
  {
    id: "31",
    name: "Ella Perez",
    email: "ella@email",
    status: "Paid",
    date: "03-03-2024",
    avatar: "https://i.pravatar.cc/40?img=31",
    plan: "6 Months",
  },
  {
    id: "32",
    name: "Alexander Roberts",
    email: "alexander@email",
    status: "Expired",
    date: "03-03-2024",
    avatar: "https://i.pravatar.cc/40?img=32",
    plan: "Yearly",
  },
  {
    id: "33",
    name: "Scarlett Turner",
    email: "scarlett@email",
    status: "Paid",
    date: "03-03-2024",
    avatar: "https://i.pravatar.cc/40?img=33",
    plan: "Monthly",
  },
  {
    id: "34",
    name: "Matthew Phillips",
    email: "matthew@email",
    status: "Expired",
    date: "03-03-2024",
    avatar: "https://i.pravatar.cc/40?img=34",
    plan: "6 Months",
  },
  {
    id: "35",
    name: "Aria Campbell",
    email: "aria@email",
    status: "Paid",
    date: "03-04-2024",
    avatar: "https://i.pravatar.cc/40?img=35",
    plan: "Yearly",
  },
  {
    id: "36",
    name: "Joseph Parker",
    email: "joseph@email",
    status: "Expired",
    date: "03-04-2024",
    avatar: "https://i.pravatar.cc/40?img=36",
    plan: "Monthly",
  },
  {
    id: "37",
    name: "Grace Evans",
    email: "grace@email",
    status: "Paid",
    date: "03-04-2024",
    avatar: "https://i.pravatar.cc/40?img=37",
    plan: "6 Months",
  },
  {
    id: "38",
    name: "Samuel Edwards",
    email: "samuel@email",
    status: "Expired",
    date: "03-04-2024",
    avatar: "https://i.pravatar.cc/40?img=38",
    plan: "Yearly",
  },
  {
    id: "39",
    name: "Chloe Collins",
    email: "chloe@email",
    status: "Paid",
    date: "03-05-2024",
    avatar: "https://i.pravatar.cc/40?img=39",
    plan: "Monthly",
  },
  {
    id: "40",
    name: "Daniel Stewart",
    email: "danielstewart@email",
    status: "Expired",
    date: "03-05-2024",
    avatar: "https://i.pravatar.cc/40?img=40",
    plan: "6 Months",
  },
  {
    id: "41",
    name: "Victoria Morris",
    email: "victoria@email",
    status: "Paid",
    date: "03-05-2024",
    avatar: "https://i.pravatar.cc/40?img=41",
    plan: "Yearly",
  },
  {
    id: "42",
    name: "Logan Rogers",
    email: "logan@email",
    status: "Expired",
    date: "03-05-2024",
    avatar: "https://i.pravatar.cc/40?img=42",
    plan: "Monthly",
  },
  {
    id: "43",
    name: "Lily Cook",
    email: "lily@email",
    status: "Paid",
    date: "03-06-2024",
    avatar: "https://i.pravatar.cc/40?img=43",
    plan: "6 Months",
  },
  {
    id: "44",
    name: "Jacob Morgan",
    email: "jacob@email",
    status: "Expired",
    date: "03-06-2024",
    avatar: "https://i.pravatar.cc/40?img=44",
    plan: "Yearly",
  },
  {
    id: "45",
    name: "Zoe Bell",
    email: "zoe@email",
    status: "Paid",
    date: "03-06-2024",
    avatar: "https://i.pravatar.cc/40?img=45",
    plan: "Monthly",
  },
  {
    id: "46",
    name: "Mason Reed",
    email: "mason@email",
    status: "Expired",
    date: "03-06-2024",
    avatar: "https://i.pravatar.cc/40?img=46",
    plan: "6 Months",
  },
  {
    id: "47",
    name: "Ella Bailey",
    email: "ellabailey@email",
    status: "Paid",
    date: "03-07-2024",
    avatar: "https://i.pravatar.cc/40?img=47",
    plan: "Yearly",
  },
  {
    id: "48",
    name: "Carter Rivera",
    email: "carter@email",
    status: "Expired",
    date: "03-07-2024",
    avatar: "https://i.pravatar.cc/40?img=48",
    plan: "Monthly",
  },
  {
    id: "49",
    name: "Hannah Foster",
    email: "hannah@email",
    status: "Paid",
    date: "03-07-2024",
    avatar: "https://i.pravatar.cc/40?img=49",
    plan: "6 Months",
  },
  {
    id: "50",
    name: "Andrew Gray",
    email: "andrew@email",
    status: "Expired",
    date: "03-07-2024",
    avatar: "https://i.pravatar.cc/40?img=50",
    plan: "Yearly",
  },
];
